---
name: "Release"
on:
  push:
    tags:
      - "v*"
jobs:
  tagged-release:
    name: "Tagged Release"
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        java: [17]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - run: java -version
      - run: mvn -version
      - run: mvn --errors --batch-mode clean package -DskipTests=true
      - run: mv target/*-jar-with-dependencies.jar target/logic-checker.jar
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release.tar.gz,target/logic-checker.jar"